### ISSUE TITLE
It's "more stable" than 0.0.1

### ISSUE THREAD

**Issue by schmunk42** [codemix/yii2-streamlog#1]
We're using this great piece of code since a while without any problems.
A `1.0.0` release would be fine, even without code changes.

**Comment by mikehaertl** [comment]
Why does this matter? We may still add features or do minor changes in the API.

**Comment by phpnode** [comment]
@mikehaertl people get put off by such low version numbers, but I agree it shouldn't really matter

**Comment by schmunk42** [comment]
I just noticed it. I'd prefer to require something like `1.*` or `~1.1.2` in example, without having to worry about BC. And from the 33 lines of source-code I just thought there won't be that many BC-breaking changes ;)

Btw ... just because we're talking about version numbers. Our apps broke from 1.0 to 1.1 here https://github.com/codemix/yii2-localeurls/releases - the 1.1 release should have been a 2.0, IMHO.

It's not about nagging you with version numbers, we rely heavily on your packages and since the code-quality of your repos is always high-class, I thought it would be an issue (or something to note).

Let me know, if I should not post any further issues about versioning - no hard feelings ;)

**Comment by phpnode** [comment]
@schmunk42 I think you're right, using `0.0.1` is fine during the first few weeks of development but as soon as we actually start using this stuff it should be `1.0.0`, otherwise there's little point using semver.

**Comment by mikehaertl** [comment]
Released 1.0.0.

> Btw ... just because we're talking about version numbers. Our apps broke from 1.0 to 1.1 here https://github.com/codemix/yii2-localeurls/releases - the 1.1 release should have been a 2.0, IMHO.

Sorry for that. In my head I'm still using the old PRADO/Yii versioning scheme, where BC breaking changes were acceptable for minor version changes (e.g. from 1.0 to 1.1). I'll try to keep semver in mind from now on.
