### ISSUE TITLE
Tracelevel

### ISSUE THREAD

**Issue by bianchi** [codemix/yii2-streamlog#10]
Is it possible to set tracelevel to 0? I'm using this configuration but still getting strack trace at logs

`'log' => [
            'traceLevel' => 0,
            'targets' => [
                [
                    'class' => 'codemix\streamlog\Target',
                    'url' => 'php://stdout',
                    'levels' => ['info','trace'],
                    'prefixString' => 'YII2 => ',
                    'logVars' => [],
                ],
                [
                    'class' => 'codemix\streamlog\Target',
                    'url' => 'php://stderr',
                    'levels' => ['error', 'warning'],
                    'prefixString' => 'YII2 => ',
                    'logVars' => [],
                ],
            ],
        ],`

**Comment by mikehaertl** [comment]
`traceLevel` is not a property of a log target (and thus not related to our library) but of the `log` component:

```php
'components' => [
    'log' => [
        'traceLevel' => 0
        'targets' => [ ... ]
```
