### ISSUE TITLE
no log displayed

### ISSUE THREAD

**Issue by grptx** [codemix/yii2-streamlog#7]
Hi,
i installed your package in my app deployed with docker-compeser.
but i don't see any log displayed 
maybe i miss somewhats?

**Comment by schmunk42** [comment]
Did you configure `logTargets` according to https://github.com/codemix/yii2-streamlog#installation-and-configuration? Do you view the logs with `docker-compose logs -f`?

**Comment by grptx** [comment]
this is my config:
```
'log' => [
            'traceLevel' => 3,
            'flushInterval' => 1,
            'targets' => [
                [
                    'class' => 'codemix\streamlog\Target',
                    'url' => 'php://stdout',
                    'levels' => ['info', 'trace'],
                    'logVars' => [],
                ],
                [
                    'class' => 'codemix\streamlog\Target',
                    'url' => 'php://stderr',
                    'levels' => ['error', 'warning'],
                ],
            ],
        ],
```
and using `docker-compose logs -f` i see only the apache logs
i have this apache log config:
```
root@13b1c9c3a600:/var/log/apache2# ls -l
total 0
lrwxrwxrwx 1 www-data www-data 11 Nov 28 22:47 access.log -> /dev/stdout
lrwxrwxrwx 1 www-data www-data 11 Nov 28 22:47 error.log -> /dev/stderr
lrwxrwxrwx 1 www-data www-data 11 Nov 28 22:47 other_vhosts_access.log -> /dev/stdout

```

**Comment by mikehaertl** [comment]
I'd say this is rather an issue somewhere in your docker image. Our library here is so simple, there's little that can go wrong. Can you e.g. do a simple test and write a standalone PHP script (without Yii or any framwork) that writes to stdout and check if you see the output there?

**Comment by bstuff** [comment]
@grptx , if you are using console application, try set `'exportInterval' => 1,` in codemix\streamlog\Target. That helped me.

**Comment by grptx** [comment]
he proble was related to te use of this template: https://github.com/hoaaah/yii2-micro
using basc-template there is no problem
thx all
